:Author: ard12sgf1960
:Email:
:Date: 23/10/2023
:Revision: version#
:License: Public Domain

= Project:

Using M5 Modules to remotely control relays using Arduino IOT and integral push buttons

== Step 1: Installation
1. Connect the relay module to the M5 Stick
2. Connect the M5 Stick to a PC with Arduino IDE
3. Add your WiFi credentials and Arduino Secret ID
4. Upload the code to the device

=== Folder structure

....
 LED_Control                => Arduino sketch folder
  ├── LED_Control.ino       => main Arduino file
  ├── arduino_secrets.h     => library that holds your WiFi credentials
  ├── pbHelper.h            => library that manages the integral push buttons
  ├── relayHelper.h         => library that manages the relay module
  ├── thingProperties.h     => Arduino created library 
  └── ReadMe.adoc           => this file
....

=== License
This project is released under a {Public} License.

=== Contributing
To contribute to this project please contact: sgfpcb@gmail.com or visit GitHub https://github.com/SF1960/M5_Dual_Relay.git

=== BOM
Add the bill of the materials you need for this project.

|===
| ID | Part name       | Part number | Quantity
| A1 | M5StickCPlus1.1 | 1234-abcd   | 1     
| A2 | 2 x Relay Module| 2345-asdf   | 1           
|===


=== Help
In depth help and assistance https://docs.google.com/document/d/e/2PACX-1vTH1nJYqNYGAg056k6YIh0rXgBWlNZ1g8O2z5Eg9DDR7KSh8IV7Ok6y7FPdXnKbob_FHi-xP2Slc4QJ/pub[Code Help]
This document is written in the _AsciiDoc_ format, a markup language to describe documents. 
If you need help you can search the http://www.methods.co.nz/asciidoc[AsciiDoc homepage]
or consult the http://powerman.name/doc/asciidoc[AsciiDoc cheatsheet]
