// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "19628c90-9b69-43f4-8902-e362efa84288";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onRelay1Change();
void onRelay2Change();

bool feedback;
bool relay_1;
bool relay_2;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(feedback, READ, ON_CHANGE, NULL);
  ArduinoCloud.addProperty(relay_1, READWRITE, ON_CHANGE, onRelay1Change);
  ArduinoCloud.addProperty(relay_2, READWRITE, ON_CHANGE, onRelay2Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
